/*
===============================================================================
                        EDA – Magnitude Analysis
===============================================================================
Script Purpose:
    Quantifies key business data by grouping results across dimensions such as
    country, gender, and product category. Helps understand the relative scale
    and distribution of customers, products, and revenue across the dataset.

Queries Included:
    1. Total customers by country
       Source: gold.dim_customers
    2. Total customers by gender
       Source: gold.dim_customers
    3. Total products by category
       Source: gold.dim_products
    4. Average product cost by category
       Source: gold.dim_products
    5. Total revenue by product category
       Source: gold.fact_sales, gold.dim_products
    6. Total revenue by customer
       Source: gold.fact_sales, gold.dim_customers
    7. Total items sold by country
       Source: gold.fact_sales, gold.dim_customers

SQL Functions Used:
    - SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

--Find total products by category
SELECT
	category,
	COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

--What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

--What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
JOIN gold.dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

--What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
